apiVersion: apps/v1
kind: Deployment
metadata:
  name: sliver-fe-deployment
  labels:
    app: sliver-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sliver-fe
  template:
    metadata:
      labels:
        app: sliver-fe
    spec:
      imagePullSecrets:
        - name: harbor
      containers:
        - name: sliver
          image: harbor.sunweiwei.xyz/library/sliver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sliver-fe-svc
  labels:
    app: sliver-fe-svc
spec:
  selector:
    app: sliver-fe
  ports:
    - port: 80
      targetPort: 80
